"""add token and exp

Revision ID: 570528579823
Revises: f3971b980b49
Create Date: 2024-03-28 08:02:38.445485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570528579823'
down_revision = 'f3971b980b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
